const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt-for-men',
      category: 'Shirts',
      image: '/images/p1.jpeg',
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque volutpat ac tincidunt vitae semper. Massa tincidunt dui ut ornare lectus sit amet. Vitae turpis massa sed elementum tempus egestas sed sed risus. Facilisis mauris sit amet massa. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Neque laoreet suspendisse interdum consectetur libero id. Nunc non blandit massa enim nec dui nunc mattis. Nisl suscipit adipiscing bibendum est ultricies. Libero id faucibus nisl tincidunt eget nullam non nisi. Nibh ipsum consequat nisl vel pretium lectus quam. Eleifend donec pretium vulputate sapien nec sagittis. Purus gravida quis blandit turpis cursus in. Erat velit scelerisque in dictum non consectetur a. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce.',
    },
    {
      _id: '2',
      name: 'Addidus Sneaker',
      slug: 'addidus-sneakers-for-women',
      category: 'Shoes',
      image: '/images/p2.jpeg',
      price: 90,
      countInStock: 23,
      brand: 'Addidus',
      rating: 4.3,
      numReviews: 40,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque volutpat ac tincidunt vitae semper. Massa tincidunt dui ut ornare lectus sit amet. Vitae turpis massa sed elementum tempus egestas sed sed risus. Facilisis mauris sit amet massa. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Neque laoreet suspendisse interdum consectetur libero id. Nunc non blandit massa enim nec dui nunc mattis. Nisl suscipit adipiscing bibendum est ultricies. Libero id faucibus nisl tincidunt eget nullam non nisi. Nibh ipsum consequat nisl vel pretium lectus quam. Eleifend donec pretium vulputate sapien nec sagittis. Purus gravida quis blandit turpis cursus in. Erat velit scelerisque in dictum non consectetur a. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce.',
    },
    {
      _id: '3',
      name: 'HP Notepad 337364 Slim',
      slug: 'hp-notepad-slim-blue',
      category: 'Laptops',
      image: '/images/p3.jpeg',
      price: 1500,
      countInStock: 18,
      brand: 'HP',
      rating: 4.9,
      numReviews: 50,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque volutpat ac tincidunt vitae semper. Massa tincidunt dui ut ornare lectus sit amet. Vitae turpis massa sed elementum tempus egestas sed sed risus. Facilisis mauris sit amet massa. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Neque laoreet suspendisse interdum consectetur libero id. Nunc non blandit massa enim nec dui nunc mattis. Nisl suscipit adipiscing bibendum est ultricies. Libero id faucibus nisl tincidunt eget nullam non nisi. Nibh ipsum consequat nisl vel pretium lectus quam. Eleifend donec pretium vulputate sapien nec sagittis. Purus gravida quis blandit turpis cursus in. Erat velit scelerisque in dictum non consectetur a. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce.',
    },
    {
      _id: '4',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt-new',
      category: 'Shirts',
      image: '/images/p1.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque volutpat ac tincidunt vitae semper. Massa tincidunt dui ut ornare lectus sit amet. Vitae turpis massa sed elementum tempus egestas sed sed risus. Facilisis mauris sit amet massa. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Neque laoreet suspendisse interdum consectetur libero id. Nunc non blandit massa enim nec dui nunc mattis. Nisl suscipit adipiscing bibendum est ultricies. Libero id faucibus nisl tincidunt eget nullam non nisi. Nibh ipsum consequat nisl vel pretium lectus quam. Eleifend donec pretium vulputate sapien nec sagittis. Purus gravida quis blandit turpis cursus in. Erat velit scelerisque in dictum non consectetur a. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce.',
    },
    {
      _id: '5',
      name: 'Addidus Sneaker',
      slug: 'addidus-sneakers-for-men',
      category: 'Shoes',
      image: '/images/p2.jpeg',
      price: 90,
      countInStock: 23,
      brand: 'Addidus',
      rating: 4.3,
      numReviews: 40,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque volutpat ac tincidunt vitae semper. Massa tincidunt dui ut ornare lectus sit amet. Vitae turpis massa sed elementum tempus egestas sed sed risus. Facilisis mauris sit amet massa. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Neque laoreet suspendisse interdum consectetur libero id. Nunc non blandit massa enim nec dui nunc mattis. Nisl suscipit adipiscing bibendum est ultricies. Libero id faucibus nisl tincidunt eget nullam non nisi. Nibh ipsum consequat nisl vel pretium lectus quam. Eleifend donec pretium vulputate sapien nec sagittis. Purus gravida quis blandit turpis cursus in. Erat velit scelerisque in dictum non consectetur a. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce.',
    },
    {
      _id: '6',
      name: 'HP Notepad 337364 Slim',
      slug: 'hp-notepad-60',
      category: 'Laptops',
      image: '/images/p3.jpeg',
      price: 1500,
      countInStock: 18,
      brand: 'HP',
      rating: 4.9,
      numReviews: 50,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque volutpat ac tincidunt vitae semper. Massa tincidunt dui ut ornare lectus sit amet. Vitae turpis massa sed elementum tempus egestas sed sed risus. Facilisis mauris sit amet massa. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Neque laoreet suspendisse interdum consectetur libero id. Nunc non blandit massa enim nec dui nunc mattis. Nisl suscipit adipiscing bibendum est ultricies. Libero id faucibus nisl tincidunt eget nullam non nisi. Nibh ipsum consequat nisl vel pretium lectus quam. Eleifend donec pretium vulputate sapien nec sagittis. Purus gravida quis blandit turpis cursus in. Erat velit scelerisque in dictum non consectetur a. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce.',
    },
    {
      _id: '7',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt-bg',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '8',
      name: 'Adidas Fit Shirt',
      slug: 'addidus-fit-big',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '9',
      name: 'Lacoste Free Shirt',
      slug: 'lacaste-free-shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '10',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pants-for-men',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '11',
      name: 'Puma Slim Pant',
      category: 'Pants',
      slug: 'puma-slim-pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '12',
      name: 'Adidas Fit Pant',
      slug: 'addidus-fit-pant-for-women',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};

export default data;
